Adding the Risk Service sample for the event-driven Microservices report
redpanda-data/redpanda-examples pull request #6
Opened 2022-03-11 16:23 UTC by dunithd

Created a new folder called 'blogs' to keep the samples related to blogs. The first sample is related to the event-driven Microservices booklet.

2022-03-11 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/redpanda-examples?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/redpanda-examples?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/redpanda-examples?pullRequest=6) it.</sub>

2022-03-11 16:54 UTC, andrewhsu commented on blogs/edms-fintech/risk-service/.gitignore
> +release.properties
```suggestion
release.properties
*.jar
```

2022-03-11 16:57 UTC, andrewhsu requested changes
in general we should not store binaries in this github repo. please remove the `jar` file from this PR. it looks like there are ways for the user to retrieve the `maven-wrapper.jar` file upon clean checkout. not sure if associated blog post needs instructions updated to account for this.

2022-03-14 15:03 UTC, dunithd reviewed
Those files in the .mvn directory have been generated by the build tool. I will send a new PR after deleting it and adding an exclusion for .jar files in the .gitignore file.

2022-03-14 15:03 UTC, closed without merging